Category.create!(name: 'ALIMENTOS BÁSICOS', status: :active)
Category.create!(name: 'ALIMENTOS CONGELADOS', status: :active)
Category.create!(name: 'ARTÍCULOS PARA EL HOGAS', status: :active)
Category.create!(name: 'BEBIDAS', status: :active)
Category.create!(name: 'CARNES', status: :active)
Category.create!(name: 'CEREAL, ARROZ Y PASTAS', status: :active)
Category.create!(name: 'GALLETAS', status: :active)
Category.create!(name: 'LÁCTEOS', status: :active)
Category.create!(name: 'PANES', status: :active)
Category.create!(name: 'SALUD Y BELLEZA', status: :active)
Category.create!(name: 'SNACKS', status: :active)